version: "2.2"

services:
  mongo:
    image: mongo:5.0.4
    container_name: groot_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db:rw
      - ./init:/docker-entrypoint-initdb.d

  content:
    image: node:latest
    container_name: groot_api
    working_dir: /app
    command: npm start
    environment:
      DB_HOST: mongo
      DB_USER: content
      DB_PASSWORD: example
      CACHE_HOST: cache
    links:
      - mongo
      - cache
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/
