module.exports = {
    CONTENT: "CONTENT",
    DESCRIPTION: "DESCRIPTION",
    DIRECTORY: "DIRECTORY",
    DIRECTORY_VALUE: "DIRECTORY_VALUE",
    IMAGE: "IMAGE",
    LANG: "LANG",
    PROPERTY: "PROPERTY",
    PERMISSION: "PERMISSION",
    SECTION: "SECTION",
    STATUS: "STATUS",
    PUBLIC: "PUBLIC",
};
